apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: redpointgames/nginx-proxy
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0m
        volumeMounts:
        - mountPath: /tmp/docker.sock
          name: docker-api
          readOnly: true
        - mountPath: /etc/nginx/certs
          name: ssl-certificates
          readOnly: true
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        livenessProbe:
          exec:
            command:
            - bash
            - "-c"
            - "if [ \"$(wget -q0- http://localhost/ | grep Welcome)\" != \"\" ]; then exit 1; else exit 0; fi"
          initialDelayPeriod: 60
          periodSeconds: 5
      volumes:
      - name: docker-api
        hostPath:
          path: /var/run/docker.sock
      - name: ssl-certificates
        secret:
          secretName: ssl-certificates
        