apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: redpointgames/nginx-proxy
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 30m
            memory: 30Mi
          limits:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - mountPath: /tmp/docker.sock
          name: docker-api
          readOnly: true
        - mountPath: /etc/nginx/certs
          name: ssl-certificates
          readOnly: true
        ports:
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          exec:
            command:
            - bash
            - "-c"
            - "if [ \"$(wget -q0- http://localhost/ | grep Welcome)\" != \"\" ]; then exit 1; else exit 0; fi"
          initialDelaySeconds: 60
          periodSeconds: 5
      volumes:
      - name: docker-api
        hostPath:
          path: /var/run/docker.sock
      - name: ssl-certificates
        secret:
          secretName: ssl-certificates
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-lb
spec:
  selector:
    app: reverse-proxy
  loadBalancerIP: 104.154.189.88
  ports:
  - name: rp-http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: rp-https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer